/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-03-15 02:54:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Login | Airline Reservation</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: url(\"resources/images/plane-desktop.jpg\") no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            display: flex; justify-content: center; align-items: center;\r\n");
      out.write("            height: 100vh; text-align: center; color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.8); padding: 50px; border-radius: 30px;\r\n");
      out.write("            box-shadow: 0 25px 40px rgba(0, 0, 0, 0.15); width: 90%; max-width: 450px;\r\n");
      out.write("            backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("        h1 { font-size: 2rem; margin-bottom: 20px; color: #2c3e50; }\r\n");
      out.write("        input {\r\n");
      out.write("            width: 100%; padding: 12px; margin: 10px 0; border-radius: 8px;\r\n");
      out.write("            border: 1px solid #ccc; font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            width: 100%; padding: 12px; background: linear-gradient(45deg, #81ecec, #74b9ff);\r\n");
      out.write("            color: #fff; font-size: 1rem; font-weight: bold; border-radius: 50px;\r\n");
      out.write("            transition: all 0.3s ease, transform 0.2s ease;\r\n");
      out.write("            border: none; cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover { background: linear-gradient(45deg, #74b9ff, #81ecec); transform: scale(1.1); }\r\n");
      out.write("        .error { color: red; font-size: 0.9rem; }\r\n");
      out.write("        body { \r\n");
      out.write("    background: #BCEDFF; /* Light Blue Background */\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    color: #0E4A7B; /* Deep Blue Text for contrast */\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>🔑 Login</h1>\r\n");
      out.write("        <form action=\"login.jsp\" method=\"post\">\r\n");
      out.write("            <input type=\"email\" name=\"email\" placeholder=\"Email\" required>\r\n");
      out.write("            <input type=\"password\" name=\"password\" placeholder=\"Password\" required>\r\n");
      out.write("            <button type=\"submit\">Login</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <p>Don't have an account? <a href=\"signup.jsp\">Sign Up</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

        if ("POST".equalsIgnoreCase(request.getMethod())) {
            String email = request.getParameter("email");
            String password = request.getParameter("password");

            Connection conn = null;
            PreparedStatement stmt = null;
            ResultSet rs = null;

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline", "root", "root");

                // Corrected query to fetch user_id, user_type
                String sql = "SELECT user_id, user_type, first_name, middle_name, last_name FROM user WHERE email=? AND password=?";
                stmt = conn.prepareStatement(sql);
                stmt.setString(1, email);
                stmt.setString(2, password);
                rs = stmt.executeQuery();

                if (rs.next()) {
                    int userId = rs.getInt("user_id"); // Fetch user_id
                    String userType = rs.getString("user_type");

                    // Full Name Formatting
                    String fullName = rs.getString("first_name") + " " + 
                                      (rs.getString("middle_name") != null ? rs.getString("middle_name") + " " : "") + 
                                      rs.getString("last_name");

                    // Storing in session
                    session.setAttribute("user_id", userId);  // Store user_id
                    session.setAttribute("userEmail", email);
                    session.setAttribute("userType", userType);
                    session.setAttribute("fullName", fullName);

                    // Redirect based on user type
                    if ("Admin".equalsIgnoreCase(userType)) {
                        response.sendRedirect("admindash.jsp");
                    } else {
                        response.sendRedirect("passengerdash.jsp");
                    }
                    return; // Stop further execution
                } else {
    
      out.write("\r\n");
      out.write("                    <script>alert(\"Invalid email or password! Please try again.\");</script>\r\n");
      out.write("    ");

                }
            } catch (Exception e) {
    
      out.write("\r\n");
      out.write("                <p class='error'>Error: ");
      out.print( e.getMessage() );
      out.write("</p>\r\n");
      out.write("    ");

            } finally {
                try { if (rs != null) rs.close(); if (stmt != null) stmt.close(); if (conn != null) conn.close(); } catch (SQLException ignored) {}
            }
        }
    
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
